repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
        name: Check JSON files
        exclude: ^\.vscode/
      - id: check-yaml
        name: Check YAML files
      - id: check-toml
        name: Check TOML files
      - id: end-of-file-fixer
        name: Ensure proper file endings
      - id: trailing-whitespace
        name: Remove unnecessary whitespace from code
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        name: Lint Python code with ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        name: Format Python code with ruff
        types_or: [python, pyi, jupyter]

  - repo: local
    hooks:
      - id: ty
        name: Type check Python code with ty
        entry: uv run ty check
        language: python
        types_or: [python]

  - repo: local
    hooks:
      - id: nbconvert
        name: Strip output of Jupyter notebooks
        stages: [pre-commit]
        entry: uv run jupyter nbconvert
        args: [--clear-output, --inplace]
        language: system
        files: \.ipynb$
